### PR TITLE
Hotfix request cycle translation fixes

### PR DESCRIPTION
**Pull request by GawainLynch**
This fixes handling of translations on Bolt 2.2.5+ ([see Bolt #3948](https://github.com/bolt/bolt/issues/3948)) as after that point we enabled caching of translations.

### CODE REVIEW

**Comment by bacbos** [comment]
Having some troubles setting up a fresh bolt to review this, tried with tags 2.2.6 - 2.2.9 with no success.
Can't yet tell if there's something fishy with my current set-up or with an updated dependency that's b0rking bolt, any idea? :/

The error occurs after setting up the first user when trying to access /bolt
image

**Comment by GawainLynch** [comment]
Ah that is a combination of xdebug and Symfony. In either your `xdebug.ini` or `php.ini` you can set something like `xdebug.max_nesting_level = 500`

**Comment by bacbos** [comment]
Ah yes, it's working now, you were right. I installed my mac from scratch last week and PHP is still mostly running on the default configs.

Your PR is merged in, thanks a lot mate!

**Comment by GawainLynch** [comment]
You're very welcome… This should also make it work smoothly on Bolt 2.3 as well.

**Pull request merged**
