### PR TITLE
Some small bugfixes

### PR DESCRIPTION
**Pull request by bobdenotter**
- Make id more uniquer: Prevent placing new fields in wrong menu
 - Make the template a bit more consistent with the rest of Bolt.
 - Fix some typos.

### CODE REVIEW

**Comment by anketwokings** [comment]
Thx for fixing!

**Comment by SahAssar** [comment]
This looks good to me, I'm guessing it's been monkeytested by @bobdenotter?

**Comment by bobdenotter** [comment]
@SahAssar Yes, it has been monkeytested.

If you could merge in this one together with #70, and tag a new release, that'd be great! :-)

**Comment by SahAssar** [comment]
I've merged #70, and merging this now.

If you have the time to do a check that master works well after this that'd be great, and then when either of us have done it I can tag :)

**Comment by bobdenotter** [comment]
@SahAssar Did some more testing on dev-master, seems to work fine! 👍

**Comment by SahAssar** [comment]
Tagged now :)

**Pull request merged**
