### PR TITLE
3.0 proposal

### LINKED ISSUE #31: 3.0 support

### PR DESCRIPTION
**Pull request by SahAssar**
Righto, This is my first draft for a 3.0 version of the extension. It is fully functional but is missing some key pieces needed before release (Like some more UI work, better code structure in twig/JS/CSS, restoration of backups, updating/using translations and searching tags), but I thought I'd PR it and then perhaps get some feedback on it so far, and I'll try to finish those up in the coming days.

Most everything is changed since a lot of things are easier in 3.0, especially all filesystem related things, and because I wanted to get rid of the old Nestable plugin and RequireJS, but basic UX is the same except for searching content, which is done the way  I mentioned in #31.

Oh, and I'm planning to do the translation stuff in the style of https://github.com/bolt/bolt/pull/5292

Basic screenshot below (like I said, missing some UI work):
menueditor

Criticism/feedback is very much welcome!

Oh, and this also fixes #31 and #27.

### CODE REVIEW

**Comment by SahAssar** [comment]
And here comes the backup restoration feature:

image

**Comment by SahAssar** [comment]
So, I got the taxonomies, backup restoring and translations working again, should just be a UI touchup and a bit of code cleanup and then it's ready to go :)

**Comment by SahAssar** [comment]
IMO this should be gtg now, @bacbos any thoughts?

It of course can be polished further, but this should be enough for a first 3.1 version. Screenshot:

image

**Comment by SahAssar** [comment]
@bacbos Have you had a chance to look at this yet?

**Comment by bacbos** [comment]
Great work @SahAssar , much appreciated, thanks!

**Comment by GawainLynch** [comment]
Thanks @bacbos & @SahAssar ! :+1: 

We're going to have some happy Bolt 3.1 users soon :-)

**Pull request merged**
