### PR TITLE
BOLT_CONFIG_DIR not being initialized with the latest BOLT version

### PR DESCRIPTION
**Pull request by Raistlfiren**
Problem:
BOLT_CONFIG_DIR was not being set with the latest version of BOLT.

Fix:
I used $this->app['paths']['config'] to resolve the correct path for the configuration directory.

### CODE REVIEW

**Comment by bacbos** [comment]
Seems related to https://github.com/bacbos/bolt-menu-editor/pull/6 which I wasn't able to reproduce at the time. I'll dig a bit deeper over the weekend and get back to you. Thanks in the meantime!

**Comment by Raistlfiren** [comment]
Whoops, I should of noticed that. Thanks for the response!

**Comment by bacbos** [comment]
I'm very sorry, but I'm still not able to reproduce this, neither on my dev-mac nor on an ordinary LAMP hosting. 

I just cloned the latest codebase (https://github.com/bolt/bolt/commit/f58077c68f894b539e37bf07a50fdd9ffd18db5f) and bolt as well as the menu editor extension work out of the box as expected.

```BOLT_CONFIG_DIR``` is being set in https://github.com/bolt/bolt/blob/b9b301dc63f9aaa06a3453c1b05e06988ea6c858/src/Configuration/ResourceManager.php#L348 - in my opinion by looking at some important pieces of code, bolt would not even be able to run in the first place if this constant wasn't being set properly.

I did a quick ```echo BOLT_CONFIG_DIR; die;``` in Extension.php of the menu-editor extension and I got the correct path printed out.

Seems like everything's fine on my end, what do you suggest?

**Comment by Raistlfiren** [comment]
I was able to replicate the problem by using the composer install method - https://docs.bolt.cm/installation-composer. That is how I originally installed bolt as well. I did see the reference for the resourcemanager.php as well, but I don't believe it is being called initially in a composer install.

**Comment by bacbos** [comment]
Right!

Thanks a lot, merged it in

**Pull request closed without merging**
